INSERT
INTO
    USER
    (
        userid,
        FirstName,
        lastname,
        email,
        birthdate,
        sex,
        password
    )
    VALUES
    (
        'abtyagi',
        'Abhishek',
        'Tyagi',
        'abhishek.8in@gmail.com',
        '1982-09-17',
        'M',
        'satishusha'
    )